// this file is loaded by engine, it loads all other scripts

#include "script/base_defines.script"

// defs and util functions
#include "script/quip_defs.script"
#include "script/quip_events.script"
#include "script/quip_utils.script"

#include "script/player.script"
#include "script/weapon_base.script"
#include "script/weapon_unarmed.script"




void quip_main()
{
	sys.print( "Entering quip_main()\n");
//	game_count = 0;
	sys.print( "Exiting quip_main()\n" );
}
